# Generated by Django 3.1.3 on 2022-02-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_reviews', '0002_auto_20220206_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkedreviews',
            name='folder',
            field=models.CharField(default='Favorites', max_length=30),
        ),
    ]
